### ISSUE TITLE
Map Animation - cont. to Beta

### ISSUE THREAD

**Issue by teganscott** [polygon-studios/master#121]
Animate the map to feel life like. You have the entire beta milestone to do this. Please provide updates as you go to provide feedback from the team. You can have a lot of fun with this! If you need ideas for animations let us know, and i am sure we can help out.

**Comment by kieralundberg** [comment]
Done:
Cloud graphics
Bird animation
Leaf animation
Raven animation
Mushroom spring
Cloud disappearing
Fog animation
Star twinkle

To do:
