### ISSUE TITLE
Item Animation - cont. to Alpha

### ISSUE THREAD

**Issue by teganscott** [polygon-studios/master#123]
Animate the items. They will have a stationary animation, and a animation if they are being used. You have two weeks to complete this task.

**Comment by kieralundberg** [comment]
on hold until character animations done

**Comment by kieralundberg** [comment]
pinwheel: static animation done, wind animation done
oil: static animation done
treasure chest: static animation done, coin animation done
slippers: static animation done, slipper overlay graphic done
firework: static animation done, firework animation done
pepper: static animation done
marshmallow gun: static animation done, marshmallow projectile graphic done
pillow case: static animation done (can greyscale character as effect if pillowcase overlay too hard)
silly salmon: static animation done, fish flop animation done
prunes: static animation done

NEEDED
slipper overlay applied to all character cycles
fire animation for all character cycles
ghost animation for all character cycles
old animation for all character cycles
programmatic light brightening
programmatic marshmallow projectile

**Comment by teganscott** [comment]
Task transferred to Andrzej for completion
